### ISSUE TITLE
Use object_selector controller for custom setting

### ISSUE THREAD

**Issue by grappler** [xwp/wp-customize-object-selector#29]
Goal: Add page and posts select box with the ability to select multiple posts or pages.

I was able to use the control but was not sure how to enable the multiple option for select2 and modify the post types to query.

Any pointer would be appreciated.

**Comment by westonruter** [comment]
Here is an example of `multiple`: https://github.com/xwp/wp-js-widgets/tree/develop/post-collection-widget

**Comment by westonruter** [comment]
And an example of modifying the post types to query: https://github.com/xwp/wp-customize-object-selector/blob/e4aeef6edb4b5ba953aacfccdca2f8df42aa4042/php/class-plugin.php#L81

**Comment by grappler** [comment]
Thank you very much @westonruter! I got it work. It works really well. Look forward to getting integrated in core. This maybe the gateway into getting select2 into core.

**Comment by westonruter** [comment]
@grappler thanks! Unfortunately I have doubts as to the longevity of Select2. The most recent release was in May last year, and activity has been waning:

![image](https://cloud.githubusercontent.com/assets/134745/22040885/8108ade0-dcb9-11e6-8fe2-d358f7b479e0.png)

That being said, if another best-of-breed multi-select library becomes the de-facto and has committed long-term support, it should be straightforward to swap out the library used in this plugin.
