### ISSUE TITLE
Allow Posts page in Static Front Page to be blank

### ISSUE THREAD

**Issue by grappler** [xwp/wp-customize-object-selector#30]
In the settings the posts page can be blank

![image](https://cloud.githubusercontent.com/assets/1785641/22156348/2aec706e-df33-11e6-9c22-cad431312c79.png)

In the customizer the plugin automatically add a second page. Even when I try to remove the page the first available page is added.

![image](https://cloud.githubusercontent.com/assets/1785641/22156392/537e2e32-df33-11e6-9b89-73517e028e59.png)

**Comment by westonruter** [comment]
@grappler I remember building this intentionally. Doesn't there *have* to be a posts page assigned of a front page assigned? Otherwise, how would the posts be accessed?

**Comment by grappler** [comment]
> Doesn't there have to be a posts page assigned of a front page assigned?

No, it works fine if there is no posts page.

> Otherwise, how would the posts be accessed?

I don't need to the posts page. I have a business site that does not have a blog. 😄

**Comment by westonruter** [comment]
@grappler give #31 a try. It seems to fix the issue for me. However, in other object selector controls I am able to successfully clear the value, so I'm not really sure why the component has problems specifically with the static front page controls.

**Comment by grappler** [comment]
@westonruter Sorry for the delay. I tested it and works just as expected.
