### ISSUE TITLE
Add an edit shortcut to open a post section from Customize Posts

### ISSUE THREAD

**Issue by westonruter** [xwp/wp-customize-object-selector#8]
Just as there is an Add New button to insert a new post and add it to a Select2 (#2) each existing selected option in a Select2 should have an edit button to open that existing post's section for editing. For a multiple select, this could be an Edit icon appearing on the left of the option, where on the right there is the X to remove the option. For non-multiple, there could be a button appearing under the Select2 control to edit the selected option.

Depends on https://github.com/xwp/wp-customize-posts/issues/146 so we can fetch a post and create a section on demand.

**Comment by lgedeon** [comment]
UI concept: Add a read-only list below the select2 with details about each of the related objects and put the edit link(s) in that list. This keeps the select and sort area of the multi-select version clean and simple, and allows a consistent UI for single-select. Details help to confirm that you selected the object you intended.
